### ISSUE TITLE
Dataloader expects classes

### ISSUE THREAD

**Issue by garygazanga** [hugohadfield/pytorch_image_regession#1]
I tried to run your data_loader.py on some images organised to suit your code (i.e. topDir/train/images.png and topDir/test/images.png and topDir/train.csv and test.csv with each line as filename, val1, val2).  However, I get the following error:
Traceback (most recent call last):
  File "dataLoader.py", line 159, in <module>
    data = RegressionTaskData()
  File "dataLoader.py", line 105, in __init__
    self.trainloader = self.make_trainloader()
  File "dataLoader.py", line 120, in make_trainloader
    train_data = RegressionImageFolder(
  File "dataLoader.py", line 84, in __init__
    super().__init__(root, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 218, in find_classes
    return find_classes(directory)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/datasets/folder.py", line 42, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in /mnt/shared/Gary/motionTrain/train.

Why would it be looking for classes in a linear regression example?

**Comment by garygazanga** [comment]
It would appear that a single class subdir (of any name) in each of 'train' and 'test' gets around the problem.

**Comment by mfatihtalu** [comment]
If you change all / characters in train.xls and test.xls to \, your error will be resolved.

**Comment by hugohadfield** [comment]
Apologies @garygazanga its looking for "classes" because the easiest, minimal way to do image regression was to take the standard image classification code and modify the dataloader to add targets etc. As a result the error messages you get may be a little nonsensical. In general though, you will need to match the *exact* layout of example dataset to make it work/or we could add a bit of code to make the image loading a bit more robust etc... at the moment I have gone for the low code/lazy approach of just producing the minimum viable template and letting people mess around with it as they like :)
